### ISSUE TITLE
Org level 2 and 3 colors

### ISSUE THREAD

**Issue by noctuid** [marktran/color-theme-ujelly#15]
Could org level 2 and 3 be different colors? Currently they are hard to tell apart.

**Comment by marktran** [comment]
Sure. Just pushed an update.

![screenshot](https://dl.dropboxusercontent.com/u/476562/screenshots/Screenshot%202016-05-02%2000.59.49.png)

**Comment by noctuid** [comment]
Thanks, that looks nice!
