### ISSUE TITLE
Ruby regexp named capture group

### ISSUE THREAD

**Issue by ferfebles** [marktran/color-theme-ujelly#16]
In ruby-mode, named capture groups have the same color as the regexp. Could they be painted in another color?

p.e.

```ruby
if  /\A(?<first>\w+),\s*(?<last>\w+)\z/ =~ "Franze, Jr"
  puts "#{first} #{last}"
end

# Result:
# Franze Jr
```

All the regexp "/\A(?<first>\w+),\s*(?<last>\w+)\z/" has the same green color. But the named capture groups "first" and "last" can be used as local variables, and they should be painted different.

**Comment by marktran** [comment]
@ferfebles Does `ruby-mode` or `enh-ruby-mode` parse the capture groups as a different face? What is the name of that face?

**Comment by ferfebles** [comment]
With ruby-mode:

```
There are text properties here:
  face                 font-lock-string-face
  fontified            t
```

With enh-ruby-mode:

```
There are text properties here:
  font-lock-face       enh-ruby-regexp-face
  fontified            t
```

So, no difference between the regexp and the capture group variable :-(

**Comment by marktran** [comment]
Yeah, looks like there won't be a way to customize it in the theme.

**Comment by ferfebles** [comment]
By the way, your theme was the main culpable of me using emacs.

When I first tested emacs, I stared at its features, but it seemed so ugly... But after installing ujelly I can't stand another editor :-)

Thanks!!!

**Comment by marktran** [comment]
Aw, thanks @ferfebles 😄
