### ISSUE TITLE
Org Colors

### ISSUE THREAD

**Issue by noctuid** [marktran/color-theme-ujelly#17]
I think there could still be some improvement to the org colors. Currently, the 4th and 5th levels headings are the same color (and this repeats later). Also, it would be nice if `TODO`, `DONE`, etc. were not the same color as any of the headings (currently `TODO` is the same color as a level 2 heading and `DONE` is the same color as a level 8 heading). Thanks for the great color scheme!

**Comment by marktran** [comment]
@noctuid Thanks for the feedback!

I just pushed some changes—let me know if you any other suggestions.

![screenshot](https://www.dropbox.com/s/3nojci58l9gq4ns/Screenshot%202016-10-24%2017.53.18.png?dl=1)
