### ISSUE TITLE
No background color on graphic display

### ISSUE THREAD

**Issue by dlukes** [marktran/color-theme-ujelly#18]
Hi,

your latest commit on master (30efb05), which sets the background color to `nil` in order to respect the background color set by the terminal, introduced a bug when running Emacs on a graphic display instead of a terminal -- background colors are broken:

![broken ujelly](https://user-images.githubusercontent.com/2734517/26870342-f883ac2e-4b6f-11e7-99e2-06e68a851946.png)

The fix is straightforward, see [this diff](https://github.com/marktran/color-theme-ujelly/compare/master...dlukes:master). I can start a pull request if you'd like, or you can just copy and paste the fix yourself :)

And thanks for ujelly by the way, it's a really great theme!

**Comment by marktran** [comment]
Thanks for the patch @dlukes! It is now applied to master.
